# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

pool:
  name: az400m05l05a-pool
  demands:
  - agent.name -equals BSFD-54ZD0J3

strategy:
  matrix:
    Python36:
      python.version: '3.6.9'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.6.9'
    githubToken: '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'
    addToPath: true
    architecture: 'x64'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    pip install pytest pytest-azurepipelines
    pytest
  displayName: 'pytest'
