# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

pool:
  name: az400m05l05a-pool
  demands:
  - agent.name -equals BSFD-54ZD0J3

steps:

- task: PythonScript@0
  inputs:
    scriptSource: 'inline'
    script: |
      print('Hello world 1')
      print('Hello world 2')
    pythonInterpreter: '/home/user/Downloads/vsts-agent-linux-x64-2.206.1/_work/_tool/3.6.9'
